/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RA.h"
#define RELEASE 1

void
resourceallocator_2(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	reply result_1;
	rsrc_req  allocate_2_arg;
	enum clnt_stat retval_2;
	reply result_2;
	rsrc_req  release_2_arg;

#ifndef	DEBUG
	clnt = clnt_create ("127.0.0.1", ResourceAllocator, RA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror ("127.0.0.1");
		exit (1);
	}
#endif	/* DEBUG */

	/*--------------------------------------------*/
	/*
	 * Allocate Request for N number of Resources
	 * where N_Requested <= M_Private
	 */
	/*--------------------------------------------*/
while(1){
	allocate_2_arg.req = rand()%10;
	retval_1 = allocate_2(&allocate_2_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	
	/*Check if the results have beed reurned correctly;
	 * if It's Not; so the request is blocked
	 * due to the number of resources
	 */
	if (result_1.rep != allocate_2_arg.req*2){ 
		printf("I'm Blocked\n");
	}
	else printf("[Result:\t] %ld\n",result_1.rep);

	/*--------------------------------------------*/
	/*
	 * Release/Deallocate the Aquired Resources
	 */
	/*--------------------------------------------*/
	sleep(2);
	release_2_arg.req = allocate_2_arg.req;
	retval_2 = release_2(&release_2_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
}
	/*--------------------------------------------*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	resourceallocator_2 ("127.0.0.1");
exit (0);
}
