/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RA.h"

bool_t
allocate_2_svc(rsrc_req *argp, reply *result, struct svc_req *rqstp)
{
	bool_t retval;
	unsigned int work;

	/*
	 * insert server code here
	 * @req and @rep have been specified in "RA.x" file 
	 */	
	printf("[START:\t] Thread id = '%ld', arg = %d\n",pthread_self(),argp->req);
	/*Hack to do a dummy work on the requested resources
	 * for random duration*/
	work=rand()%3;
	sleep(work);
  	result->rep = 2*(argp->req);
  	printf("[END  :\t] Thread id = '%ld' is done %d \n",pthread_self(),result->rep);

  	//return(TRUE);

	return retval;
}

int
resourceallocator_2_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
