/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RA.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

/*[MODIFIED]--------------------------------------
 * Data Structure to be passed
 * to the thread
 */
struct thr_par //thr_data
{
	struct svc_req *rqstp;
	SVCXPRT *transp;
};

/*--------------------------------------------------------*/
/* Define the thread_id @p_thread and @attr */
pthread_t p_thread; 
pthread_attr_t attr;
/* Function/Handler Executed by the thread */

void *
serv_request(void *data)
{
	struct thr_par *ptr_par = (struct thr_par *)data;

	/*[Moved from @resourceallocator_2 function]*/	
	union {
		rsrc_req allocate_2_arg;
	} argument;
	union {
		reply allocate_2_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);
	/*[End]*/

	struct svc_req *rqstp = ptr_par->rqstp;
	register SVCXPRT *transp = ptr_par->transp;
        
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;
	
	case allocate:
		_xdr_argument = (xdrproc_t) xdr_rsrc_req;
		_xdr_result = (xdrproc_t) xdr_reply;
		local = (bool_t (*) (char *, void *,  struct svc_req *))allocate_2_svc;
		break;
	
	default:
		svcerr_noproc (transp);
		return;
	}

	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}

	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);

	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!resourceallocator_2_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");
	
	return;
}

/*[END MODIFICATION]--------------------------------------*/


/*--------------------------------------------------------*/
/* New Modification to Start Threads for each request
 *
 */
/*--------------------------------------------------------*/
/* @resourceallocator_2 is invoked each time that there is a RPC
 * from any client. Therefore, a thread is created 
 * to services this request,
 */
static void
resourceallocator_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	struct data_str
	{
		struct svc_req *rqstp;
		SVCXPRT *transp;
	} *data_ptr=(struct data_str*)malloc(sizeof(struct data_str));

	data_ptr->rqstp = rqstp;
	data_ptr->transp = transp;
	//pthread_attr_setdetachstate(&attr,PTHREAD_CREATE_DETACHED);
	pthread_create(&p_thread,&attr,serv_request,(void *)data_ptr);
	pthread_join(p_thread, NULL);
}


/*@MAIN---------------------------------------------------*/
int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (ResourceAllocator, RA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, ResourceAllocator, RA, resourceallocator_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ResourceAllocator, RA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, ResourceAllocator, RA, resourceallocator_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ResourceAllocator, RA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
