/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RA.h"

unsigned int 	rsrc_pvt=10;
unsigned int 	init=0;
pthread_mutex_t lock;

bool_t
allocate_2_svc(rsrc_req *argp, reply *result, struct svc_req *rqstp)
{
	bool_t retval;
	unsigned int work;
	
	if (!init) {
		pthread_mutex_init(&lock,NULL); /*Initialize the mutex @lock*/
		init=1;
	}
	/*
	 * insert server code here
	 * @req and @rep have been specified in "RA.x" file 
	 */

	/*For each client request, a thread is to be started
	 * @pthread_create is called in the @RA_svc.c
	 */	
	printf("[START:\t] Thread id = %d, arg = %d\n",pthread_self(),argp->req);

	while (argp->req > rsrc_pvt) {
		argp->req+=20;
		printf("Block thread %d\n",pthread_self());
		argp->req-=20;
	}

	/* 
	 * >critical section
	 * Update the resources number */

	pthread_mutex_lock(&lock);
	rsrc_pvt-=argp->req;
	pthread_mutex_unlock(&lock);

	printf("[DEBUG:\t] rsrc_pvt = %d \n",rsrc_pvt);
	/*Hack to do a dummy work on the requested resources
	 * for random duration between up to 3 secs*/
	work=rand()%9;
	sleep(work);
 
	result->rep = 2*(argp->req);
	/* 
	 * >critical section
	 * Update the resources number */
	pthread_mutex_lock(&lock);
	rsrc_pvt+=argp->req;
	pthread_mutex_unlock(&lock);


	printf("[DEBUG:\t] rsrc_pvt = %d \n",rsrc_pvt);
  	printf("[END  :\t] Thread id = %d is done %d \n",pthread_self(),result->rep);

  	//return(TRUE);

	return retval;
}

int
resourceallocator_2_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
